apiVersion: v1
kind: Service
metadata:
  name: nft-demo-backend
  labels:
    app: nft-demo
spec:
  type: NodePort
  selector:
    app: nft-demo
    tier: web
  ports:
  - port: 3000
    targetPort: 3000
---  
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nft-demo-ssl-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: nft-demo-issuer
  labels:
    app: nft-demo
spec:
  tls:
  - secretName: nft-demo-cert
    hosts:
    - nft.uno
  rules:
  - host: nft.uno
    http:
      paths:
      - backend:
          serviceName: nft-demo-backend
          servicePort: 3000
        path: /
